### ISSUE TITLE
broken on big endian platforms

### ISSUE THREAD

**Issue by hvr** [TomMD/pureMD5#5]
The following sample program

```hs
{-# LANGUAGE OverloadedStrings #-}

import Data.Digest.Pure.MD5
import Control.Monad
import System.Info

main = do
  print (os, arch)
  forM_ ["", "a", "abc"] $ \s -> print (s, md5 s, md5DigestBytes (md5 s))
```

results in differently computed MD5 sums on different `arch`s:

```hs
("linux","x86_64")
("",d41d8cd98f00b204e9800998ecf8427e,"\212\GS\140\217\143\NUL\178\EOT\233\128\t\152\236\248B~")
("a",0cc175b9c0f1b6a831c399e269772661,"\f\193u\185\192\241\182\168\&1\195\153\226iw&a")
("abc",900150983cd24fb0d6963f7d28e17f72,"\144\SOHP\152<\210O\176\214\150?}(\225\DELr")
```

```hs
("linux","powerpc64")
("",d41d8cd98f00b204e9800998ecf8427e,"\212\GS\140\217\143\NUL\178\EOT\233\128\t\152\236\248B~")
("a",f0b1c87cfc20d3d4cab3c2c0945c779f,"\240\177\200|\252 \211\212\202\179\194\192\148\\w\159")
("abc",ee86307fba667546f2cb8c5ebb7b2d52,"\238\134\&0\DEL\186fuF\242\203\140^\187{-R")
```

```hs
("aix","powerpc")
("",d98c1dd404b2008f980980e97e42f8ec,"\217\140\GS\212\EOT\178\NUL\143\152\t\128\233~B\248\236")
("a",7cc8b1f0d4d320fcc0c2b3ca9f775c94,"|\200\177\240\212\211 \252\192\194\179\202\159w\\\148")
("abc",7f3086ee467566ba5e8ccbf2522d7bbb,"\DEL0\134\238Fuf\186^\140\203\242R-{\187")
```

**Comment by TomMD** [comment]
How horrifying.

**Comment by TomMD** [comment]
I'm looking for a PPC linux machine on which I can test.  Sorry for the breakage.  Is this new or just newly discovered?

**Comment by ekmett** [comment]
I like how it isn't just 2 different answers, but 3.

**Comment by TomMD** [comment]
What I'm hearing out of band is there is a likely bug in bytestring-builder.  Since I have pressing issues on other projects I'm letting that investigation play-out and will come back to this EOD @ PDT.

**Comment by hvr** [comment]
@TomMD just to confirm, turns out that `pureMD5` is not at fault here; it's `bytestring`'s fault

**Comment by TomMD** [comment]
Thanks @hvr

**Comment by hvr** [comment]
@TomMD btw, ironically I discovered this when I used `pureMD5` as reference implementation to test `cryptohash-md5` against (https://github.com/hvr/cryptohash-md5/blob/master/src-tests/test-md5.hs) :-))
